In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import  LinearRegression
from sklearn.tree import DecisionTreeRegressor,plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor,VotingRegressor

data = pd.read_csv('bodyfat-Copy1.csv')

In [108]:
data.head()

Density  BodyFat  Age  Weight  Height  Neck  Chest  Abdomen    Hip  Thigh  \
0   1.0708     12.3   23  154.25   67.75  36.2   93.1     85.2   94.5   59.0   
1   1.0853      6.1   22  173.25   72.25  38.5   93.6     83.0   98.7   58.7   
2   1.0414     25.3   22  154.00   66.25  34.0   95.8     87.9   99.2   59.6   
3   1.0751     10.4   26  184.75   72.25  37.4  101.8     86.4  101.2   60.1   
4   1.0340     28.7   24  184.25   71.25  34.4   97.3    100.0  101.9   63.2   

   Knee  Ankle  Biceps  Forearm  Wrist  
0  37.3   21.9    32.0     27.4   17.1  
1  37.3   23.4    30.5     28.9   18.2  
2  38.9   24.0    28.8     25.2   16.6  
3  37.3   22.8    32.4     29.4   18.2  
4  42.2   24.0    32.2     27.7   17.7

In [109]:
data.isnull().sum()

Density    0
BodyFat    0
Age        0
Weight     0
Height     0
Neck       0
Chest      0
Abdomen    0
Hip        0
Thigh      0
Knee       0
Ankle      0
Biceps     0
Forearm    0
Wrist      0
dtype: int64

In [110]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 15 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Density  252 non-null    float64
 1   BodyFat  252 non-null    float64
 2   Age      252 non-null    int64  
 3   Weight   252 non-null    float64
 4   Height   252 non-null    float64
 5   Neck     252 non-null    float64
 6   Chest    252 non-null    float64
 7   Abdomen  252 non-null    float64
 8   Hip      252 non-null    float64
 9   Thigh    252 non-null    float64
 10  Knee     252 non-null    float64
 11  Ankle    252 non-null    float64
 12  Biceps   252 non-null    float64
 13  Forearm  252 non-null    float64
 14  Wrist    252 non-null    float64
dtypes: float64(14), int64(1)
memory usage: 29.7 KB


In [111]:
data.corr()

Density   BodyFat       Age    Weight    Height      Neck     Chest  \
Density  1.000000 -0.987782 -0.277637 -0.594062  0.097881 -0.472966 -0.682599   
BodyFat -0.987782  1.000000  0.291458  0.612414 -0.089495  0.490592  0.702620   
Age     -0.277637  0.291458  1.000000 -0.012746 -0.171645  0.113505  0.176450   
Weight  -0.594062  0.612414 -0.012746  1.000000  0.308279  0.830716  0.894191   
Height   0.097881 -0.089495 -0.171645  0.308279  1.000000  0.253710  0.134892   
Neck    -0.472966  0.490592  0.113505  0.830716  0.253710  1.000000  0.784835   
Chest   -0.682599  0.702620  0.176450  0.894191  0.134892  0.784835  1.000000   
Abdomen -0.798955  0.813432  0.230409  0.887995  0.087813  0.754077  0.915828   
Hip     -0.609331  0.625201 -0.050332  0.940884  0.170394  0.734958  0.829420   
Thigh   -0.553091  0.559608 -0.200096  0.868694  0.148436  0.695697  0.729859   
Knee    -0.495040  0.508665  0.017516  0.853167  0.286053  0.672405  0.719496   
Ankle   -0.264890  0.265970 -0.105058  0.613685  0.264744  0.477892  0.482988   
Biceps  -0.487109  0.493271 -0.041162  0.800416  0.207816  0.731146  0.727907   
Forearm -0.351648  0.361387 -0.085056  0.630301  0.228649  0.623660  0.580173   
Wrist   -0.325716  0.346575  0.213531  0.729775  0.322065  0.744826  0.660162   

          Abdomen       Hip     Thigh      Knee     Ankle    Biceps   Forearm  \
Density -0.798955 -0.609331 -0.553091 -0.495040 -0.264890 -0.487109 -0.351648   
BodyFat  0.813432  0.625201  0.559608  0.508665  0.265970  0.493271  0.361387   
Age      0.230409 -0.050332 -0.200096  0.017516 -0.105058 -0.041162 -0.085056   
Weight   0.887995  0.940884  0.868694  0.853167  0.613685  0.800416  0.630301   
Height   0.087813  0.170394  0.148436  0.286053  0.264744  0.207816  0.228649   
Neck     0.754077  0.734958  0.695697  0.672405  0.477892  0.731146  0.623660   
Chest    0.915828  0.829420  0.729859  0.719496  0.482988  0.727907  0.580173   
Abdomen  1.000000  0.874066  0.766624  0.737179  0.453223  0.684983  0.503316   
Hip      0.874066  1.000000  0.896410  0.823473  0.558387  0.739273  0.545014   
Thigh    0.766624  0.896410  1.000000  0.799170  0.539797  0.761477  0.566842   
Knee     0.737179  0.823473  0.799170  1.000000  0.611608  0.678709  0.555898   
Ankle    0.453223  0.558387  0.539797  0.611608  1.000000  0.484855  0.419050   
Biceps   0.684983  0.739273  0.761477  0.678709  0.484855  1.000000  0.678255   
Forearm  0.503316  0.545014  0.566842  0.555898  0.419050  0.678255  1.000000   
Wrist    0.619832  0.630090  0.558685  0.664507  0.566195  0.632126  0.585588   

            Wrist  
Density -0.325716  
BodyFat  0.346575  
Age      0.213531  
Weight   0.729775  
Height   0.322065  
Neck     0.744826  
Chest    0.660162  
Abdomen  0.619832  
Hip      0.630090  
Thigh    0.558685  
Knee     0.664507  
Ankle    0.566195  
Biceps   0.632126  
Forearm  0.585588  
Wrist    1.000000

In [112]:
data.describe()

Density     BodyFat         Age      Weight      Height        Neck  \
count  252.000000  252.000000  252.000000  252.000000  252.000000  252.000000   
mean     1.055574   19.150794   44.884921  178.924405   70.148810   37.992063   
std      0.019031    8.368740   12.602040   29.389160    3.662856    2.430913   
min      0.995000    0.000000   22.000000  118.500000   29.500000   31.100000   
25%      1.041400   12.475000   35.750000  159.000000   68.250000   36.400000   
50%      1.054900   19.200000   43.000000  176.500000   70.000000   38.000000   
75%      1.070400   25.300000   54.000000  197.000000   72.250000   39.425000   
max      1.108900   47.500000   81.000000  363.150000   77.750000   51.200000   

            Chest     Abdomen         Hip       Thigh        Knee       Ankle  \
count  252.000000  252.000000  252.000000  252.000000  252.000000  252.000000   
mean   100.824206   92.555952   99.904762   59.405952   38.590476   23.102381   
std      8.430476   10.783077    7.164058    5.249952    2.411805    1.694893   
min     79.300000   69.400000   85.000000   47.200000   33.000000   19.100000   
25%     94.350000   84.575000   95.500000   56.000000   36.975000   22.000000   
50%     99.650000   90.950000   99.300000   59.000000   38.500000   22.800000   
75%    105.375000   99.325000  103.525000   62.350000   39.925000   24.000000   
max    136.200000  148.100000  147.700000   87.300000   49.100000   33.900000   

           Biceps     Forearm       Wrist  
count  252.000000  252.000000  252.000000  
mean    32.273413   28.663889   18.229762  
std      3.021274    2.020691    0.933585  
min     24.800000   21.000000   15.800000  
25%     30.200000   27.300000   17.600000  
50%     32.050000   28.700000   18.300000  
75%     34.325000   30.000000   18.800000  
max     45.000000   34.900000   21.400000

In [113]:
X=data[['Biceps','Knee','Thigh','Hip','Abdomen','Chest','Weight']]
y=data['BodyFat']

In [114]:
X.shape

(252, 7)

In [115]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=10)
X_train

Biceps  Knee  Thigh    Hip  Abdomen  Chest  Weight
239    35.9  38.1   59.2  100.5    100.5  106.4  189.75
210    30.9  35.0   51.1   89.0     79.4   91.2  140.50
233    27.8  35.9   56.8  100.2     94.9   94.9  161.75
78     31.4  37.5   53.5   99.3     95.4   96.4  161.25
25     29.9  36.7   55.0   96.5     79.7   89.6  159.25
..      ...   ...    ...    ...      ...    ...     ...
64     35.3  41.2   65.0  108.3    105.5  105.3  205.50
15     31.1  38.7   63.1   99.2     92.8   99.1  162.75
228    34.6  37.4   58.4   98.4     89.4  104.0  174.50
125    35.6  36.0   60.7  100.0     89.9  101.0  167.00
9      35.6  41.7   63.1  104.1     88.6   99.6  198.25

[168 rows x 7 columns]

In [116]:
sc= StandardScaler()
X=sc.fit_transform(X)
X

array([[-0.09067593, -0.53613146, -0.07747885, ..., -0.68353321,
        -0.91804761, -0.84124583],
       [-0.58814329, -0.53613146, -0.13473595, ..., -0.88796263,
        -0.85862095, -0.19346239],
       [-1.15193963,  0.12859242,  0.03703534, ..., -0.43264256,
        -0.59714363, -0.84976929],
       ...,
       [-0.32282736, -0.53613146,  0.17063524, ...,  1.76032756,
         1.22131225,  0.26680479],
       [-0.58814329,  1.25031395, -0.65004983, ...,  0.81251844,
         0.88852294,  0.40318025],
       [ 0.47312041,  1.4995854 , -0.02022175, ...,  1.48156017,
         1.37582157,  0.97425249]])

## Linear model

In [117]:
model=LinearRegression()

In [118]:
model.fit(X_train,y_train)

LinearRegression()

In [119]:
y_pred= model.predict(X_test)
y_pred

array([26.94015422, 14.24747436, 24.71079882, 18.32718412, 19.98578136,
       19.29902615,  2.638222  , 32.42077281, 31.96515158,  3.44494849,
        4.25191519, 18.43048713, 16.28786878, 22.81160638,  7.99777124,
       13.10643148, 27.55572844,  5.54218746, 20.28324036, 24.69668555,
       25.61340194, 19.18837642, 16.88644289, 16.52643258, 18.13221389,
       22.68509674,  7.70561631, 36.96759299,  8.24003812, 36.36874217,
       10.0558891 , 24.21110151, 23.62720638, 21.79881135, 10.81186892,
       15.53535219, 18.82473581,  7.40588853,  7.00478893, 23.85970495,
       22.6079289 , 13.66343735, 25.68089921, 16.37275676, 23.65935481,
        8.97091695, 17.5746486 , 21.5017047 , 23.37843703, 21.31380983,
       17.54973659, 19.47993986, 29.53819384,  6.47100668, 20.56272828,
       18.77256629, 10.48163476, 14.88804785, 23.05653896,  9.43233181,
       26.3817108 , 16.12856744, 15.60773183, 15.03440207, 21.72393492,
       32.0678733 , 18.59337278, 18.72095011, 11.58892781, 23.52

In [120]:
model.intercept_

-64.02550789523325

In [121]:
model.coef_

array([ 0.44702905,  0.12884852,  0.25117444, -0.03002881,  1.07444034,
       -0.03614311, -0.24830972])

In [122]:
model.score(X_train,y_train)

0.7182886095452256

In [123]:
model.score(X_test,y_test)

0.7173604427559548

In [124]:
mean_squared_error(y_test,y_pred,squared=False)

4.501246466050954

## Decision Tree Model

In [125]:
model1= DecisionTreeRegressor(max_depth=5)

In [126]:
model1.fit(X_train,y_train)

DecisionTreeRegressor(max_depth=5)

In [127]:
y_pred1= model1.predict(X_test)
y_pred1

array([27.44      , 10.4625    , 29.09      , 25.975     , 23.6       ,
       20.78947368,  3.7       , 29.09      , 29.09      ,  0.7       ,
        0.7       , 20.78947368, 13.45      , 24.1       ,  3.7       ,
       13.45      , 27.44      , 10.43461538, 20.6375    , 29.09      ,
       29.09      , 20.6375    , 15.6       , 13.45      , 10.4625    ,
       24.1       , 13.45      , 29.09      ,  9.6       , 29.09      ,
       10.43461538, 29.09      , 25.47272727, 20.78947368, 10.4625    ,
       19.51818182, 20.1       , 10.43461538, 10.43461538, 24.1       ,
       20.1       , 15.6       , 20.78947368, 15.6       , 31.13333333,
        9.6       , 25.975     , 20.78947368, 25.47272727, 20.78947368,
       20.78947368, 15.6       , 29.09      ,  3.7       , 20.78947368,
       10.4625    , 13.45      , 13.45      , 20.78947368, 10.43461538,
       29.09      , 20.78947368, 13.45      , 15.6       , 25.47272727,
       29.09      , 10.4625    , 25.47272727, 13.45      , 20.63

In [128]:
model1.score(X_train,y_train)

0.8572878275336655

In [129]:
model1.score(X_test,y_test)

0.611425251390618

In [130]:
mean_squared_error(y_test,y_pred1,squared=False)

5.277808262864325

## using Voting Regressor model

In [164]:
estimator = []
estimator.append(('LR', LinearRegression()))
estimator.append(('RFR',RandomForestRegressor(max_depth=20)))
estimator.append(('DTC', DecisionTreeRegressor(max_depth=30)))

In [165]:
model2= VotingRegressor(estimators=estimator)
model2.fit(X_train, y_train)

VotingRegressor(estimators=[('LR', LinearRegression()),
                            ('RFR', RandomForestRegressor(max_depth=20)),
                            ('DTC', DecisionTreeRegressor(max_depth=30))])

In [166]:
y_pred2 = model2.predict(X_test)
y_pred2

array([26.73438474, 11.90615812, 28.66726627, 21.43272804, 20.99459379,
       19.43400872,  4.947074  , 31.87259094, 27.93338386,  4.69498283,
        4.39197173, 20.91616238, 18.24362293, 23.90920213,  6.40159041,
       16.31147716, 26.77424281,  6.11439582, 20.77241345, 25.59489518,
       27.93280065, 18.86245881, 17.14148096, 14.23814419, 16.0440713 ,
       23.66469891, 10.7758721 , 31.99819766,  9.44734604, 29.80291406,
        7.4436297 , 28.01903384, 22.19206879, 20.04193712, 10.52795631,
       17.82778406, 20.91591194,  9.50562951,  9.28459631, 24.88956832,
       22.47630963, 14.35847912, 22.3569664 , 18.25491892, 25.82911827,
        9.26363898, 21.68654953, 20.93756823, 22.21981234, 22.53560328,
       19.77957886, 18.59897995, 29.94006461,  5.60766889, 18.92124276,
       15.67585543,  9.53421159, 14.05268262, 22.62717965,  8.28477727,
       25.84423693, 19.07452248, 13.52224394, 16.47446736, 23.54864497,
       28.32362443, 15.25245759, 21.81065004, 15.0946426 , 21.25

In [167]:
model2.score(X_train,y_train)

0.9411886460830515

In [168]:
model2.score(X_test,y_test)

0.7131231862254799

In [170]:
mean_squared_error(y_test,y_pred2,squared=False)

4.5348616877641